#! /bin/bash

#  Copyright (c) 2011 James Peach
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

author=$(git config --get user.name)

mkheader()
{
    if [ -e "$1" ] ; then
        echo $1 exists
        return
    fi

    echo making $1

    path="$1"
    name=`basename "$1"`
    year=`date +%Y`
    uuid=`uuidgen`

    guard=`echo ${name}_${uuid} | tr a-z A-Z | sed 's/[-. ]/_/g' `

cat > "$path" <<EOF
/*
 * Copyright (c) ${year} $author
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef $guard
#define $guard

#endif /* $guard */
/* vim: set sw=4 ts=4 tw=79 et : */
EOF
}

while : ; do
    if [ -z "$1" ]; then
        exit
    fi

    mkheader "$1"
    shift
done

# vim: set sw=4 ts=4 tw=79 et :
